### PR TITLE
Predictor encoding and sub image fixes

### LINKED ISSUE #9: 16-bit png encoding not supported
I create a BufferedImage with TYPE_USHORT_GRAY, ImageIO.write will encode this properly as 16-bit grayscale, but PngEncoder saves it as 8-bit truecolor.

### PR DESCRIPTION
**Pull request by rototor**
I tried to regroup the changes into sensible commits. If you wish me to split up the changes in a different way, just say so.

This PR does those things:
- Adds a predictor encoder, which decreases file size but at the same time of course increases ZLib compression time, as ZLib has more stuff to save space but also has to do it.
- Fix #9 by supporting 16 bit images correctly
- Correctly handle sub-images
- Support non sRGB color spaces by embedding ICC color profiles.
- Small performance improvement when encoding the image without predictor (by streaming the image rows).

The objectplanet PNG encoder still compresses a little bit better, but this is now good enough for my use cases. You can always get smaller images by using pngcrush, ImageOptim and so on. But they also take a lot more time to process the images.

Please also make performance tests on your platforms, as I only tested the performance on M1 Max chips. The performance should be improved also a little bit on x64 - but I did not measure it.

After #14, #15, #16 and #17 are merged I can rebase this PR if you wish.

### CODE REVIEW

**Comment by johantiden** [comment]
I've merged the others now! Please rebase!

**Comment by rototor** [comment]
I've rebased, please review.

**Comment by johantiden** [comment]
FYI: Benchmarks can be found in https://github.com/pngencoder/pngencoder/pull/14.
I haven't had time to consider all of this yet. For Looklet, response time is much more important than size so we might need to opt out. I'd say this PR is a major even though it doesn't break the API, because it changes the default behavior (for higher compression levels).

**Comment by johantiden** [comment]
I like sane defaults as a rule of thumb. We can add a new flag when we bump the dependency to this. I'm also very interested in the performance gains! The most time-critical parts we have are running in google compute on `n1` type machines.

I'm going on vacation tomorrow so I will probably not have time to look into this until May.
@jkaving @oloflarsson

File: src/main/java/com/pngencoder/PngEncoderLogic.java [hunk 1]
```diff
@@ -51,23 +55,25 @@ class PngEncoderLogic {
     private PngEncoderLogic() {
     }
 
-    static int encode(BufferedImage bufferedImage, OutputStream outputStream, int compressionLevel, boolean multiThreadedCompressionEnabled, PngEncoderSrgbRenderingIntent srgbRenderingIntent, PngEncoderPhysicalPixelDimensions physicalPixelDimensions) throws IOException {
+    static int encode(BufferedImage bufferedImage, OutputStream outputStream, int compressionLevel,
+            boolean multiThreadedCompressionEnabled, PngEncoderSrgbRenderingIntent srgbRenderingIntent,
+            PngEncoderPhysicalPixelDimensions physicalPixelDimensions, boolean usePreditor) throws IOException {
```
Comment (johantiden) [inline src/main/java/com/pngencoder/PngEncoderLogic.java:60]: Typo :sweat_smile: 
```suggestion
            PngEncoderPhysicalPixelDimensions physicalPixelDimensions, boolean usePredictor) throws IOException {
```

**Comment by johantiden** [comment]
Some more benchmarks from my linux laptop with Intel i7-7820HQ:

```
pngencoder develop 642de83
Benchmark                                                           Mode  Cnt    Score   Error  Units
PngEncoderBenchmarkPngEncoderVsImageIO.logo2121x350PngEncoder      thrpt       162.227          ops/s
PngEncoderBenchmarkPngEncoderVsImageIO.looklet4900x6000PngEncoder  thrpt         0.167          ops/s
PngEncoderBenchmarkPngEncoderVsImageIO.random1024x1024PngEncoder   thrpt        36.457          ops/s


rototor/predictor_encoding_and_subimage_fixes e1bf2d9
Benchmark                                                           Mode  Cnt    Score   Error  Units
PngEncoderBenchmarkPngEncoderVsImageIO.logo2121x350PngEncoder      thrpt       178.681          ops/s
PngEncoderBenchmarkPngEncoderVsImageIO.looklet4900x6000PngEncoder  thrpt         0.166          ops/s
PngEncoderBenchmarkPngEncoderVsImageIO.random1024x1024PngEncoder   thrpt        39.021          ops/s

```
With those benchmarks, it seems 7-10% faster, except for the very large image which is marginally slower.

**Comment by johantiden** [comment]
And the custom test

pngencoder develop 642de83
```
[467] PngEncoder Warmup
[437] PngEncoder Result 0
[424] PngEncoder Result 1
[445] PngEncoder Result 2
[435] PngEncoder Result 3
[404] PngEncoder Result 4
[414] PngEncoder Result 5
[426] PngEncoder Result 6
[442] PngEncoder Result 7
[404] PngEncoder Result 8
[409] PngEncoder Result 9
```
rototor/predictor_encoding_and_subimage_fixes e1bf2d9
```
[380] PngEncoder Warmup
[364] PngEncoder Result 0
[420] PngEncoder Result 1
[371] PngEncoder Result 2
[371] PngEncoder Result 3
[393] PngEncoder Result 4
[365] PngEncoder Result 5
[391] PngEncoder Result 6
[371] PngEncoder Result 7
[388] PngEncoder Result 8
[396] PngEncoder Result 9
```

**Comment by rototor** [comment]
Shit, this Github instant rename commits are silly... I fix this branch...

**Comment by johantiden** [comment]
> Shit, this Github instant rename commits are silly... I fix this branch...

Oops :)

File: src/main/java/com/pngencoder/PngEncoder.java [hunk 2]
```diff
@@ -28,29 +30,47 @@ public class PngEncoder {
...
-            BufferedImage bufferedImage,
-            int compressionLevel,
-            boolean multiThreadedCompressionEnabled,
+    private final PredictorEncoding predictorEncoding;
+
+    private enum PredictorEncoding {
+        DEFAULT {
+            @Override
+            boolean isEnabled(int compressionLevel, boolean multiThreadedCompressionEnabled) {
+                return compressionLevel >= 6 && !multiThreadedCompressionEnabled;
```
Comment (johantiden) [inline src/main/java/com/pngencoder/PngEncoder.java:39]: I can't make up my mind. I'm on the fence between this "sane" default or whether "as fast as possible" should be the default.

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I guess we can still claim to be "very fast" because this feature can simply be turned off for very intense applications.

Comment (rototor) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I'm indifferent here. I don't have a problem with making this a simple boolean with false being the default.

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: BTW, why would the predictor be disabled by default when running multi-threaded?

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I made a separate branch just to wrap my head around this. I refactored the (now) three compression arguments into a class, moving validation and defaults to there.
264de04

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I can't seem to create a reverse Pull Request into your branch. I'd probably have to create a new fork off of your branch and make a Pull Request from there into your branch. meh.

Comment (rototor) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: Beside this being a API breaking change, it looks good.

I planing to contribute my indexed PNG encoder I built some years ago (after this changes are merged). That would be another compression setting. (i.e. tryWithIndexEncoding - as indexed only allows 256 colors this can and will fail for many images). So putting it into its one class makes sense.

Should I just try to pull your changes into this branch?

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: Try it!
1b85b9f

Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I actually like that we would break the API. The users should consider whether they want to use the new predictor or not. Since it might be turned on by default on higher compression levels (which is also nice).

Comment (rototor) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: I did a comment on the commit. After thinking a little bit about it I don't like an extra compression setting class.

To not surprise existing users we can also just default to not use the predictor by default. 

And give some examples in the README.md how to configure for maximum speed, minimal file size etc.

**Comment by johantiden** [comment]
Let's do this!

File: src/main/java/com/pngencoder/PngEncoder.java (hunk 2 above)
Comment (johantiden) [reply src/main/java/com/pngencoder/PngEncoder.java:39]: https://github.com/pngencoder/pngencoder/issues/26

**Comment by johantiden** [comment]
`0.13.0` is now published to maven central!
